### ISSUE TITLE
Should `vue` actually being a dependency instead of peerDependency?

### ISSUE THREAD

**Issue by xsjcTony** [zyyv/vue-flow-layout#1]
I recently updated `unocss` from `0.63.4` to `0.63.6`, and it's breaking my previous ESLint settings a little bit.

As I can see in this PR https://github.com/unocss/unocss/pull/4214, this package was added, and because `vue` is a `dependency`, it's been installed automatically by npm.
![image](https://github.com/user-attachments/assets/820e9295-2edd-4fca-8fd8-817c899259e2)

Since my ESLint config is automatically checking whether the `vue` package exists to determine whether to turn on vue related rules (as it requires installing `eslint-plugin-vue`), it's breaking there. My project is a React project so those rules should definitely not being turned on.

For now I can just add `vue: false` to my eslint config, which is not a big deal, but I don't really think `vue` should be a `dependency` here. `peerDependency` makes more sense to me. The unocss inspector is already there before `0.63.5`, so It's kind of a bug(?) due to the above PR?

**Comment by zyyv** [comment]
@xsjcTony  I'm a little busy, would you like to help me send a PR improvements?

**Comment by xsjcTony** [comment]
PR #2
